version: "3.9"

services:
  db:
    image: postgres:15.0
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=os.getenv("POSTGRES_USER")
      - POSTGRES_PASSWORD=os.getenv("POSTGRES_PASSWORD")
      - POSTGRES_DB=os.getenv("POSTGRES_DB")